### ISSUE TITLE
Visibility for Guests? 

### ISSUE THREAD

**Issue by zuron7** [netchampfaris/wiki#1]
Is there any way to use this wiki internally without having a guest view enabled? Super nice project and fills the void left by the in built knowledge base app in ERPNext.

**Comment by harshit-30** [comment]
@netchampfaris this is the same issue we are currently facing as well, https://sitename.com/wiki/home is public for some reason.

**Comment by zuron7** [comment]
Looks like this has been fixed with an option for each page that says visible to guests. Thank you very much.
